# Generated by Django 3.2 on 2021-05-02 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='blanks',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
