# Generated by Django 3.2 on 2021-05-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_phonenumber_blanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='blanks',
        ),
    ]
